"""added credits system in users

Revision ID: be0d98b38eb7
Revises: 016ecc59f2be
Create Date: 2026-01-11 21:46:15.594505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0d98b38eb7'
down_revision = '016ecc59f2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable with default value
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=True, server_default='3'))
    
    # Update existing rows to have default value
    op.execute("UPDATE users SET credits = 3 WHERE credits IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
